name: tagmak
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  bloc: ^9.0.0
  carousel_slider: ^5.0.0
  dartz: ^0.10.1
  equatable: ^2.0.7
  firebase_auth: ^5.5.3
  firebase_core: ^3.13.0
  flexify: ^2.1.1
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_spinkit: ^5.2.1
  flutter_svg: ^2.1.0
  get_it: ^8.0.3
  google_fonts: ^6.2.1
  google_maps_flutter: ^2.12.1
  intl_phone_field: ^3.2.0
  modal_bottom_sheet: ^3.0.0
  persistent_bottom_nav_bar_v2: ^6.0.1
  pin_code_fields: ^8.0.1
  provider: ^6.1.5

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/logo/
    - assets/images/
  # - assets/svgs/
  # - assets/fonts/
